export const _ = undefined

export const BOOLEAN = 'boolean'
export const NUMBER = 'string'
export const DEFAULT = 'default'
export const DURATION = 'duration'
export const EASING = 'easing'
export const INITIAL = 'initial'
export const NAME = 'name'
export const SELECT = 'select'
export const STATES = 'states'
export const S_SCENE = 's-scene'
export const S_STATE = 's-state'
export const S_TARGET = 's-target'
export const S_TRANSITION = 's-transition'
export const STEEL_TARGET = '__steel_target__'
export const TRANSITION = 'transition'
